### PR TITLE
fix: moving concave polygon

### PR DESCRIPTION
**Pull request by jmankopf**
update the position of the convexPolygons when moving the "parent" polygon body

Issue: #42

### CODE REVIEW

**Comment by Prozi** [comment]
thanks. can you separate to a private function and also use in setters of x and y ?

good job finding this and thanks for pr

**Comment by Prozi** [comment]
better yet a protected function in case someone wants to extend/override it

**Comment by Prozi** [comment]
thinking of it again in x setter we need just update x

so a common method wont do. just copy the code to setters and remove the irrevelant part (updates of y in setter of x are not needed and vice versa)

**Comment by Prozi** [comment]
on the other hand this is cleaner

i leave it up to you to decide

**Comment by jmankopf** [comment]
I think separating x and y would not be worth it.

**Pull request merged**
